"""empty message

Revision ID: 550f895414ec
Revises: 24ad3e250c4c
Create Date: 2022-11-29 10:21:38.967328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550f895414ec'
down_revision = '24ad3e250c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
